### ISSUE TITLE
"Latest" tag points to old release

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus-core#1]
Hi,

Issue:
It seems the "Latest" tag on Docker Hub points to an old release, while "Latest" of Unimus points correctly to the latest release. This causes a version miss-match when using "Latest" image of both Unimus and Core.

Suggested fix:
"Latest" should point to the latest Core release :)

**Comment by crocandr** [comment]
Hi,

Thank you!
I missed the latest tag update in the build process, sorry. I've fixed it.
