### ISSUE TITLE
Possible version mismatch issue or docker noob

### ISSUE THREAD

**Issue by irussellps** [crocandr/docker-unimus-core#5]
Hi, 
I am using a Synology NAS to run the Unimus-core docker image and it appears after it downloads the new image from https://registry.hub.docker.com/r/croc/unimus-core/ it logs during start up that it is version 2.1.0, my Unimus install is on version 2.1.1 after the update, apparently core won't talk to Unimus if there is a version mismatch now.

If I knew how to manually update the docker image on the Synology NAS I would give that a go for troubleshooting but I don't know how or even if that is possible seeing as it grabs the image directly from docker hub.

Thanks

**Comment by tomaskir** [comment]
The `latest` tag in Core does not yet point to `2.1.1`, you can fix this by manually pinning the version to 2.1.1 by using `croc/unimus-core:2.1.1` :)

**Comment by tomaskir** [comment]
No problem at all - glad to hear you got it working! :)
